var config = {
  PACKET_FLAG_ENCRYPT_MASK: 0x80,
  PACKET_FLAG_ACK_MASK: 0x40,
  PACKET_FLAG_LAST_PACKET_MASK: 0x20,

  PACKET_CMD_CONFIG_STA: 0x0A,
  PACKET_CMD_CONFIG_AP: 0x0B,
  PACKET_CMD_CONFIG_APSTA: 0x0C,
  PACKET_CMD_QUERY_COFNIG: 0x0D,
  PACKET_CMD_WIFI_SCAN: 0x0E,
  PACKET_CMD_KEY_EXCHANGE: 0x0F,
  PACKET_CMD_ACK: 0x10,

  PACKET_RESP_CMD_CONFIG_STA: 0x8A,
  PACKET_RESP_CMD_CONFIG_AP: 0x8B,
  PACKET_RESP_CMD_CONFIG_APSTA: 0x8C,
  PACKET_RESP_CMD_QUERY_COFNIG: 0x8D,
  PACKET_RESP_CMD_WIFI_SCAN: 0x8E,
  PACKET_RESP_CMD_KEY_EXCHANGE: 0x8F,
  PACKET_RESP_CMD_ACK: 0x90,

  PACKET_TLV_TYPE_AP_SSID: 0x01,
  PACKET_TLV_TYPE_AP_PASSWORD: 0x02,
  PACKET_TLV_TYPE_AP_BSSID: 0x03,
  PACKET_TLV_TYPE_SOFT_AP_SSID: 0x04,
  PACKET_TLV_TYPE_SOFT_AP_PASSWORD: 0x05,
  PACKET_TLV_TYPE_SOFT_AP_MAX_CN: 0x06,
  PACKET_TLV_TYPE_SOFT_AP_AUTH_MODE: 0x07,
  PACKET_TLV_TYPE_SOFT_AP_CHANNEL: 0x08,
  PACKET_TLV_TYPE_PUB_KEY: 0x09,

  PACKET_RESP_TLV_TYPE_ERROR_ID: 0x81,
  PACKET_RESP_TLV_TYPE_IP_ADDR: 0x82,
  PACKET_RESP_TLV_TYPE_MAC: 0x83,
  PACKET_RESP_TLV_TYPE_SOFTAP_IP_ADDR: 0x84,
  PACKET_RESP_TLV_TYPE_SOFTAP_MAC: 0x85,
  PACKET_RESP_TLV_TYPE_WIFI_SCAN_RESULT: 0x86,
  PACKET_RESP_TLV_TYPE_PUB_ENC_KEY: 0x87,

  MAX_LENGHT_SSID: 32,
  MAX_LENGHT_PWD: 64,
  MAX_LENGHT_CUSTOMDATA: 64,
  HEX_LENGTH_BSSID:17,

  STATUS_SUCCESS: 0,
  STATUS_INVALID_PARAMS: 1,
  STATUS_PASSWORD: 2,
  STATUS_DHCP_IP: 3,
  STATUS_WIFI_SCAN: 4,
  STATUS_NEGOTIATE_SECRET_KEY: 5,
  STATUS_GATT_WRITE: 6,
  STATUS_TIMEOUT: 7,
  STATUS_BT_POWER_OFF: 8,
  STATUS_LOCATION_DISABLE: 9,

  ORGANIZATION_ID_KEY: 'BleWiFi_Organization_Id_key'
}
module.exports = config